services:
  postgres:
    image: postgres:16-alpine
    container_name: budget-db
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - budget_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budget_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  budget_data:
